- hosts: tag_Name_os1
  tasks:
  - name: configure docker setup
    get_url:
        url: "https://download.docker.com/linux/centos/docker-ce.repo"
        dest: "/etc/yum.repos.d/"

  - name: install docker after setup the repo
    package:
      name: docker-ce
      state: present

  - name: after install the docker start the service
    service:
      name: "docker"
      state: started
  
  - name: Pull docker image from docker
    docker_image:
      name: "httpd"
      source: pull
