- hosts: web
  tasks:
  - name: configure docker setup
    get_url:
        url: "https://download.docker.com/linux/centos/docker-ce.repo"
        dest: "/etc/yum.repos.d/"

  - name: install docker after setup the repo
    package:
      name: podman
      state: present

  - name: after install the docker start the service
    service:
      name: "podman"
      state: started
  

  - name: install pip3
    package:
      name: "python3-pip"
      state: present

  - name: docker py
    pip:
      name: "podman-py"
      state: present


  - name: Pull docker image from docker
    command: podman pull httpd



  
